site_name: RATHNA SCHOOLS
site_url: https://pythonprograms.rathnaschools.com
site_author: RATHINAVELKUMAR M
site_description: >-
  An interactive site to solve lot of coding problems using python language

nav:
    - Area of the triangle: index.md
    - Solve quadratic equations: 2_quadratic_equations.md

markdown_extensions:
  - attr_list
  - md_in_html

theme:
  name: material

extra:
  analytics:
    provider: google
    property: G-##########
  social:
  - icon: fontawesome/solid/globe
    link: https://www.rathnaschools.com