site_name: RATHNA SCHOOLS
site_url: https://pythonprograms.rathnaschools.com
site_author: RATHINAVELKUMAR M
site_description: >-
  An interactive site to solve lot of coding problems using python language

nav:
    - Python program 1: index.md

theme:
  name: material

extra:
  analytics:
    provider: google
    property: G-##########
  social:
  - icon: fontawesome/solid/globe
    link: https://www.rathnaschools.com